version: '3'

services:
  web:
    platform: linux/x86_64
    container_name: nginx
    build: ./docker/nginx/
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html/
    networks:
      - internal
  php:
    platform: linux/x86_64
    container_name: app
    build: ./docker/php/
    depends_on:
      - composer_installer
    networks:
      - internal
    volumes:
      - .:/var/www/html/
    command: php-fpm

  composer_installer:
    platform: linux/x86_64
    container_name: composer_installer
    image: composer:latest
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html/
    command: >
      sh -c "composer install --optimize-autoloader && composer cc && composer dump-autoload"

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql-container
    networks:
      - internal
    volumes:
      - dbdata:/var/lib/mysql/
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test

networks:
  internal:
    driver: bridge

volumes:
  dbdata:
    driver: local
