<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWLVBvCF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWLVBvCF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWLVBvCF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWLVBvCF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWLVBvCF\App_KernelDevDebugContainer([
    'container.build_hash' => 'WLVBvCF',
    'container.build_id' => '16eece2b',
    'container.build_time' => 1676558981,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWLVBvCF');
